.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TXITERM 1 "February 26, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
txiterm \- X terminal emulator for Thai (TIS-620) environments
.SH SYNOPSIS
.B txiterm
.RI [ xiterm+thai-options ]
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBtxiterm\fP is a wrapper around the \fBxiterm+thai(1)\fP program that invokes the later program with Thai support and also loads the Thai font. 
.br
All arguments to \fBtxiterm\fP are passed to xiterm+thai without processing; 
.br
the \-fn option should not be specified because it is used by the wrapper.
.sp
See the xiterm+thai manual page for more information on \fUxiterm+thai-options\fP.
.sp
\fBNote: txiterm\fP needs \fBnectec18\fP - X Thai TIS-620 font from the  
.br
\fBxfonts-thai-nectec\fP package to allow the program to render the proper Thai text in the terminal.
.SH SEE ALSO
.BR xiterm+thai(1)
.br
.SH AUTHOR
txiterm was written by Chanop Silpa-Anan <chanop@debian.org>.
.PP
This manual page was written by Neutron Soutmun <neo.neutron@gmail.com>,
for the Debian project (but may be used by others).
