#! /bin/sh
# Chanop Silpa-Anan <chanop@debian.org>

if test "x$XMODIFIERS" = "x" ; then
	XMODIFIERS="@im=none"
fi
LANG=th_TH

export LANG XMODIFIERS

if [ $# = 0 ]; then
  exec /usr/bin/xiterm -fn nectec18 -cursorColor yellow -cursorColorThai red
else
  exec /usr/bin/xiterm -fn nectec18 $*
fi
